version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:8080"
    environment:
      - FLASK_ENV=development
    volumes:
      # Mount the current directory for development
      - .:/app
    restart: unless-stopped 